"""Update database

Revision ID: 969400da6ec0
Revises: 409e91ec78c2
Create Date: 2023-08-22 16:02:09.864286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969400da6ec0'
down_revision = '409e91ec78c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_exp',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('dict_id', sa.Integer(), nullable=False),
    sa.Column('exactly_times', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'dict_id')
    )
    with op.batch_alter_table('dictionary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dictionary_word'), ['word'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dictionary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dictionary_word'))

    op.drop_table('user_exp')
    # ### end Alembic commands ###
